author: pauhull
name: BedWars
version: 1.0
main: de.novusmc.bedwars.BedWars
load: POSTWORLD
softdepend: [Multiverse-Core, NickAPI, NpcApi]

commands:
  npc:
  setlocation:
  spawner:
  bed:
  start:
  stats: